# Generated by Django 5.1.2 on 2024-10-29 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="art",
            options={"ordering": ["-value"]},
        ),
    ]
