# Generated by Django 4.2.16 on 2024-10-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0002_alter_art_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="value",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")]
            ),
        ),
    ]
